language: node_js
node_js:
- '0.11'
- '0.10'
after_success:
- make coveralls
- '[[ -n "$TRAVIS_TAG" ]] && make gh-pages'
deploy:
  provider: npm
  email: rr.rossmann@gmail.com
  api_key:
    secure: lymx6KUjS8daJ+zEhzY2wqn4u8gsbOHBzbtLiNba9IHCCQp/tBhT57TcIKABuf+GzsOFQcINuMNoTe/eMN2bzkYaX5zx5zTmcdKfBN+jv52cah3rwQG6SXdORbuRq8Z9d7DjvO2hgV03pCMMZdLXfl6BctRwRCwLbguDzN3lP+s=
  on:
    node: '0.10'
    tags: true
    repo: Dreamscapes/Logful
    all_branches: true
matrix:
  allow_failures:
  - node_js: '0.11'
env:
  global:
    secure: BC2nXaBIFznNBCA6klgiuYBzUX4+3odZhwfWZDjOdAdYR8pWmd8btSFd3JHsRIZ0BopRao0TXVGRARQkdP/FE0W0z2zDuAieH7MN5/jRbUOzZ042+80i617zsxvtQh0/fEjFLl8UL+IKsHkMIPoZ/c1DlQPWmQ87Dsw1tarXDGQ=
