language: node_js
node_js:
- "0.11"
- "0.10"
before_install:
- npm install -g grunt-cli
after_success:
- grunt coverage:publish
deploy:
  provider: npm
  email: rr.rossmann@gmail.com
  api_key:
    secure: lymx6KUjS8daJ+zEhzY2wqn4u8gsbOHBzbtLiNba9IHCCQp/tBhT57TcIKABuf+GzsOFQcINuMNoTe/eMN2bzkYaX5zx5zTmcdKfBN+jv52cah3rwQG6SXdORbuRq8Z9d7DjvO2hgV03pCMMZdLXfl6BctRwRCwLbguDzN3lP+s=
  on:
    node: "0.10"
    tags: true
    repo: Dreamscapes/Logful
    all_branches: true
matrix:
  allow_failures:
  - node_js: "0.11"
